print("Desafio 026")
frase = str(input("Digite uma frase: ")).strip()
print(f"A letra A aparece {frase.upper().count('A')} veze(s) na frase!")
print(f"A primeira letra A apareceu na posição {frase.find('A')+1}!")
print(f"O último A aparece na posição {frase.rfind('A')+1}!")
